# This file stores all file paths , schema , database config

paths:
    raw_data : "sales_data/raw"
    processed_data : "sales_data/processed"
    archive : "sales_data/archive"
    logs : "logs/etl_logs.log"

schema:
    columns:
      - date
      - region
      - product
      - sales
      - quantity

database:
    name : salesdb
    user : postgres
    password : guptaRia123
    host : localhost
    port : 5433
    table: transactions
    # add schema also
